#### general settings
name: SFTMD_x2
use_tb_logger: true
model: sftmd
distortion: sr
scale: 2
gpu_ids: [0, 1]
kernel_size: 21
code_length: 10
sig_min: 0.2
sig_max: 2.0

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGTker
    dataroot_GT: /data/DIV2K_Flickr2K/x2HR.lmdb
    dataroot_LQ: /data/DIV2K_Flickr2K/x2LR.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    GT_size: 128
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set5
    mode: LQGTker
    dataroot_GT: /data/Set5/Set5_HR.lmdb
    dataroot_LQ: /data/Set5/Set5_LR_x2.lmdb

#### network structures
network_G:
  which_model_G: SFTMD # SRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 2
  code_length: 10

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  T_period: [125000, 125000, 125000, 125000]
  restarts: [125000, 250000, 375000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l2
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3